# Generated by Django 6.1 on 2026-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddSession',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=None, max_length=50, null=True)),
                ('status', models.CharField(blank=None, max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Dor', models.DateTimeField(null=True)),
                ('Dou', models.DateTimeField(null=True)),
                ('Dod', models.DateTimeField(null=True)),
            ],
        ),
    ]
