# Generated by Django 6.1 on 2026-09-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('academic_session', models.CharField(blank=None, max_length=20, null=True)),
                ('course_code', models.CharField(blank=None, max_length=20, null=True)),
                ('course_name', models.CharField(blank=None, max_length=50, null=True)),
                ('level', models.CharField(blank=None, max_length=50, null=True)),
                ('duration', models.CharField(blank=None, max_length=10, null=True)),
                ('status', models.CharField(blank=None, max_length=10, null=True)),
                ('description', models.CharField(blank=None, max_length=100, null=True)),
                ('Dor', models.DateTimeField(null=True)),
                ('Dou', models.DateTimeField(null=True)),
                ('Dod', models.DateTimeField(null=True)),
            ],
        ),
    ]
