# Generated by Django 6.1 on 2026-09-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSubject',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('course', models.CharField(blank=None, max_length=50, null=True)),
                ('subject_code', models.CharField(blank=None, max_length=50, null=True)),
                ('subject_name', models.CharField(blank=None, max_length=50, null=True)),
                ('semester', models.CharField(blank=None, max_length=20, null=True)),
                ('credits', models.IntegerField(blank=None, max_length=20, null=True)),
                ('teacher', models.CharField(blank=None, max_length=50, null=True)),
                ('status', models.CharField(blank=None, max_length=20, null=True)),
                ('description', models.CharField(blank=None, max_length=100, null=True)),
                ('Dor', models.DateTimeField(null=True)),
                ('Dou', models.DateTimeField(null=True)),
                ('Dod', models.DateTimeField(null=True)),
            ],
        ),
    ]
