# Generated by Django 6.1 on 2026-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_addsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTeacher',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=None, max_length=20, null=True)),
                ('teacher_name', models.CharField(blank=None, max_length=50, null=True)),
                ('email', models.EmailField(blank=None, max_length=50, null=True)),
                ('mobile', models.CharField(blank=None, max_length=13, null=True)),
                ('department', models.CharField(blank=None, max_length=50, null=True)),
                ('designation', models.CharField(blank=None, max_length=50, null=True)),
                ('username', models.CharField(blank=None, max_length=50, null=True)),
                ('password', models.CharField(blank=None, max_length=50, null=True)),
                ('status', models.CharField(blank=None, max_length=20, null=True)),
                ('Dor', models.DateTimeField(null=True)),
                ('Dou', models.DateTimeField(null=True)),
                ('Dod', models.DateTimeField(null=True)),
            ],
        ),
    ]
