# Generated by Django 6.1 on 2026-09-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_addteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addteacher',
            name='teacher_name',
            field=models.CharField(default='Unknown Teacher', max_length=50),
            preserve_default=False,
        ),
    ]
