# Generated by Django 6.1 on 2026-09-23 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_addteacher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('Enrollment_no', models.CharField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
