# Generated by Django 6.1 on 2026-09-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_addstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='Enrollment_no',
            new_name='enrollment_no',
        ),
    ]
