# Generated by Django 6.1 on 2026-09-24 06:29

import builtins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_email_addstudent_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSM',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('material_type', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('material_file', models.FileField(null=True, upload_to='study_material/')),
                ('external_url', models.CharField(verbose_name=builtins.max)),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
