# Generated by Django 6.1 on 2026-09-24 07:12

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_uploadsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsm',
            name='external_url',
            field=models.CharField(blank=True, null=True, verbose_name=builtins.max),
        ),
    ]
