# Generated by Django 6.1 on 2026-09-24 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_uploadsm_external_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('due_date', models.DateField()),
                ('course', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('total_marks', models.DecimalField()),
                ('attachment', models.FileField(null=True, upload_to='add_task')),
                ('status', models.CharField(max_length=20)),
                ('instruction', models.CharField(max_length=200)),
                ('Dor', models.DateTimeField(null=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
