# Generated by Django 6.1 on 2026-09-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_addtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtask',
            old_name='Dor',
            new_name='Dor_date',
        ),
    ]
