# Generated by Django 6.1 on 2026-09-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_dor_addtask_dor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
