# Generated by Django 6.1 on 2026-09-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_googlecredential_googlemeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Enrollment_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=16)),
                ('Date', models.DateTimeField(null=True)),
                ('teacher_name', models.CharField(max_length=100)),
            ],
        ),
    ]
