# Generated by Django 6.1 on 2026-09-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_attendance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Enrollment_no',
            new_name='enrollment_no',
        ),
    ]
