# Generated by Django 6.1 on 2026-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('audience', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
