# Generated by Django 6.1 on 2026-09-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('test_title', models.CharField(max_length=200)),
                ('test_date', models.DateField()),
                ('course', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
