# Generated by Django 6.1 on 2026-10-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
