# Generated by Django 6.1 on 2026-10-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_tasksubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
